- src/components/DetailBannerSlider/DetailBannerSlider.js
- src/pages/Detail/Detail.js
- src/pages/Router.js
> Add: Detail페이지 router연결, fetch

- src/components/DetailBannerSlider/DetailBannerSlider.js
- src/pages/Detail/Detail.js
> Refactoring: 불필요한 라인 삭제

- src/pages/Reservation/Reservation.js
- src/pages/Router.js
<br />
- reservation router 세팅
> Add: reservation router 세팅

- src/pages/Login/Login.js
- src/pages/Login/Login.module.scss
- [ x] 레이아웃 구현
- [ x] 기능 추가
<br />
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현
<br />
1. 로그인 입력 데이터 유효성 검사 (프론트)
<br />
> feature/login PR LOGIN

- src/components/ReservationSlider/ReservationSlider.js
- src/pages/Detail/Detail.js
- src/pages/Reservation/Reservation.js
- src/pages/Router.js
<br />
- reservation-slider fetch
> Add: reservation-slider fetch

- src/pages/Login/Login.module.scss
- [x ] 컨벤션 수정
<br />
<br />
<br />
<br />
> Fix: 컨벤션 수정

- src/components/Header/Header.js
- src/components/Header/Header.module.scss
> Modify: 메인 banner css수정(반응형)

- src/components/Like/Like.js
- src/components/Like/Like.module.scss
> fix:like-button 수정

- src/pages/Detail/Detail.js
- src/pages/Detail/Detail.module.scss
> Fix: detailpage 임시commit

- src/components/Header/Header.js
- src/components/Header/Header.module.scss
<br />
- Add: navigate설정, css수정
> Add: navigate설정, css수정

- src/pages/Detail/Detail.js
- src/pages/Detail/Detail.module.scss
- src/pages/Detail/RoomInfoImg.js
- src/pages/Detail/RoomInfoImg.module.scss
- src/pages/Detail/RoomInfoSlider.js
- src/pages/Detail/RoomsInfoSlider.module.scss
> fix: 디테일페이지 기능 및 css수정

- src/pages/Reservation/Reservation.js
- src/pages/Reservation/ReservationHeader.js
- src/pages/Reservation/ReservationHeader.module.scss
- [x ] 레이아웃 구현
reservation page 레이아웃완료
> PR: reservation page

- package.json
> Fix: package.json 수정

- src/pages/Detail/Detail.js
> Fix: api 수정

- src/pages/Detail/Detail.js
- src/pages/Home/components/MainBannerSlider/MainBannerSlider.js
<br />
- Fix: API 연결 확인
<br />
> Fix: API 연결 확인

- src/pages/Findstay/Findstay.js
<br />
fix: component 분리
<br />
<br />
<br />
> fix: component 분리

- src/pages/Findstay/Findstay.js
<br />
- header에서 findstay클릭시 fetch가 안되는 오류 해결
<br />
<br />
<br />
> Fix: header에서 findstay클릭시 fetch가 안되는 오류 해결

- src/components/WhenModal/WhenModalForReservation.js
- src/pages/Reservation/components/ReservationHeader/ReservationHeader.js
- src/pages/Reservation/components/ReservationHeader/ReservationHeader.module.scss
<br />
- reservation페이지 날짜선택 및 예약페이지 이동
<br />
<br />
<br />
> Add: reservation페이지 날짜선택 및 예약페이지 이동

- src/components/WhenModal/WhenModalForReservation.js
- src/pages/Reservation/Reservation.js
- src/pages/Reservation/components/ReservationHeader/ReservationHeader.js
<br />
- Add: 예약 날짜 선택 시, 결제금액 표기
<br />
<br />
> Add: 예약 날짜 선택 시, 결제금액 표기

- src/pages/Reservation/components/ReservationHeader/ReservationHeader.js
<br />
- Add: 쿼리에 room_id 추가
<br />
<br />
<br />
> Add: 쿼리에 room_id 추가

- src/pages/Findstay/Filter/Filter.js
- src/pages/Findstay/Filter/SelectPeople/SelectPeople.js
- src/pages/Findstay/Filter/SelectPrice/MultiRangeSlider.js
- src/pages/Findstay/Filter/SelectPrice/SelectPrice.js
- src/pages/Findstay/Filter/SelectTheme/SelectTheme.js
- src/pages/Findstay/Filter/SelectType/SelectType.js
- src/pages/Findstay/Findstay.js
<br />
-Fix: Filter 쿼리 1차 수정
<br />
<br />
<br />
> Fix: Filter 쿼리 1차 수정

- src/components/Header/Header.js
- src/pages/Findstay/Filter/Filter.js
- src/pages/Findstay/Filter/Order/Order.js
- src/pages/Findstay/Filter/SelectPeople/SelectPeople.js
- src/pages/Findstay/Filter/SelectPrice/MultiRangeSlider.js
- src/pages/Findstay/Filter/SelectPrice/SelectPrice.js
- src/pages/Findstay/Filter/SelectTheme/SelectTheme.js
- src/pages/Findstay/Filter/SelectType/SelectType.js
<br />
- Fix: findstay filter선택 시, 쿼리 중복 오류 수정
<br />
<br />
<br />
> Fix: findstay filter선택 시, 쿼리 중복 오류 수정

- src/components/Calendar/CheckInOut.module.scss
- src/components/WhenModal/WhenModal.module.scss
<br />
1. checkInOut 달력 모달의 오류 수정
2. WhenModal의 css구성 변경
> Fix: 달력 모달 css 오류 수정

- src/pages/Detail/components/FAQ/FAQ.js
- src/pages/Payment/Payment.js
- src/pages/Payment/Payment.module.scss
<br />
- 결제 페이지 데이터 띄우기 및 모달 창 형성
<br />
1. 예약 페이지에서 선택한 날짜 및 가격이 결제페이지 상에서 보일 수 있게 형성
2. 백엔드로 부터 받아온 예약자 정보 보일 수 있게 형성
<br />
- 아직 비로그인으로 접근 시, 접근제한 모달 창 형성이 안되었습니다...
> Payment 페이지 및 FAQ.js 정리

- src/pages/Payment/Payment.js
<br />
1. 비로그인 시 예약페이지 에서 로그인 필요 alert띄우기
> Fix: 결제페이지 비로그인 기능 추가
